name: delete releases
on: push

jobs: 
  delete-release:
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: dork7/react_native_app 
          keep_latest: 3
          delete_tag_pattern: beta 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}