name: Build and release expo app
on:
  push:
    branches:
      - "release"

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # - name: 📦 Install dependencies
      #   run: yarn install

      # - name: Build APK
      #   run: eas build --profile preview --platform android --non-interactive --clear-cache

      - name: GET APK URL from EXPO  
        run: eas build:list --json --limit=1 --platform=android |  jq -r .[0].artifacts.buildUrl

      - name: Store apk download URL in env variable
        run: echo "apk_url=$(eas build:list --json --limit=1 --platform=android |  jq -r .[0].artifacts.buildUrl)" >> $GITHUB_ENV

      - name: Download apk file
        uses: suisei-cn/actions-download-file@v1
        id: downloadfile # Remember to give an ID if you need the output
        with:
          url: 'Downloading APK from [this](${{ env.apk_url }})!'
          target: public/
          auto-match: true
      - name: LIST DIR
        run: ls -R

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: hamzameh122@gmail.com,hamxa2266@gmail.com
          # Required sender full name (address can be skipped):
          from: Developer # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully! | APK URL -> ${{ env.apk_url }}
          # Optional HTML body read from file:
          # html_body: file://README.html
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments: attachments.zip,git.diff,./dist/static/*.js
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low

      - uses: thedoctor0/zip-release@master
        with:
          path: public/
          filename: demo-app.zip

      - name: Create Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}

      - name: Upload asset to Github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./demo-app.zip
          asset_name: demo-app-v${{ github.run_number }}.zip
          asset_content_type: application/zip


  delete-release:
    runs-on: ubuntu-latest
    needs: update
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: dork7/react_native_app 
          keep_latest: 2
          # delete_tag_pattern: beta 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}